version: '2'
services:
  producer:
    image: mvf/producer:0.1
  consumer:
    image: mvf/consumer:0.1
  persistor:
    image: mvf/persistor:0.1
    depends_on:
      - java-jam-mongo
  java-jam-mongo:
    image: mongo
    ports:
     - "27017:27017"
  web:
    image: mvf/web:0.1
    ports:
     - "8080:8080"



